name: py37
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - applaunchservices=0.2.1=py_0
  - appnope=0.1.0=py37_0
  - argh=0.26.2=py37_0
  - asn1crypto=1.3.0=py37_0
  - astroid=2.3.3=py37_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2020.4.5.2=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py37_0
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py37ha12b0ac_0
  - curl=7.67.0=ha441bb4_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - docutils=0.16=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - fiona=1.8.4=py37h9a122fd_0
  - flake8=3.7.9=py37_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - freexl=1.0.5=h1de35cc_0
  - future=0.18.2=py37_0
  - gdal=2.3.3=py37hbe65578_0
  - geopandas=0.6.1=py_0
  - geos=3.7.1=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - giflib=5.1.4=h1de35cc_1
  - glib=2.63.1=hd977a24_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h4b95b61_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - imagesize=1.2.0=py_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=233
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jedi=0.15.2=py37_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.2=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.1.0=py_0
  - jupyterlab_server=1.1.1=py_0
  - kealib=1.4.7=hf5ed860_6
  - keyring=21.1.1=py37_2
  - kiwisolver=1.1.0=py37h0a44026_0
  - krb5=1.16.4=hddcf347_0
  - lazy-object-proxy=1.4.3=py37h1de35cc_0
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.67.0=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgdal=2.3.3=h0950a36_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.37=ha441bb4_0
  - libpq=11.2=h051b688_0
  - libsodium=1.0.16=h3efe00b_0
  - libspatialindex=1.9.3=h0a44026_0
  - libspatialite=4.3.0a=h644ec7d_19
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.9=hf6e021a_1
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=8.2.0=py_0
  - munch=2.5.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1g=h1de35cc_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py37h6c726b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.2=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37h4655f20_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h1de35cc_0
  - pluggy=0.13.1=py37_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.9=0
  - proj4=5.2.0=h0a44026_1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.7.0=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.1=py_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.20=py_0
  - pydocstyle=4.0.1=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=1.9.6=py37h9c430a6_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.16.0=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - pytest=5.4.1=py37_0
  - python=3.7.7=hfe9666f_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.10=py37_0
  - python.app=2=py37_10
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py37h1de35cc_0
  - pyzmq=18.1.1=py37h0a44026_0
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.7.0=py_0
  - qtconsole=4.7.3=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.23.0=py37_0
  - rope=0.16.0=py_0
  - rtree=0.9.3=py37_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - shapely=1.6.4=py37he8793f5_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.14.0=py37_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.1.0=py37_0
  - sphinx=2.4.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.2=py37_0
  - spyder-kernels=1.9.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h1de35cc_1
  - tqdm=4.45.0=py_0
  - traitlets=4.3.3=py37_0
  - ujson=1.35=py37h1de35cc_0
  - urllib3=1.25.8=py37_0
  - watchdog=0.10.2=py37h1de35cc_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h1de35cc_1
  - wurlitzer=2.0.0=py37_0
  - xerces-c=3.2.2=h44e365a_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.1.7=hc338f04_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=h0a44026_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
prefix: /Users/nick/opt/anaconda3/envs/py37

